### ISSUE TITLE
java.lang.NullPointerException 

### ISSUE THREAD

**Issue by emry78** [RWTH-i5-IDSG/steve#798] opened 2022-04-07 06:02 UTC
#### Checklist

- [ /] I checked other issues already, but found no answer/solution
- [/ ] I checked the documentation and wiki, but found no answer/solution
- [ 3.4.8] I am running the latest version and the issue still occurs
- [ /] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.8
Operating system  : Ubuntu 21.04
JDK               : 11.0.13
Database          : 10.5.13
```

#### Expected Behavior
Can display number of connected jason charge point.
...

#### Actual Behavior
when click number of connected jason charge point button from home. After click it display "java.lang.NullPointerException ".

...
**from Home:**
![Screenshot 2022-04-07 133523](https://user-images.githubusercontent.com/49600677/162130102-6d6e73de-c83b-4e1e-9a85-84660de5a20a.jpg)

**page after clicking number of connected jason charge point button** 
![Screenshot 2022-04-07 133414](https://user-images.githubusercontent.com/49600677/162130138-23a6eb1e-b2af-48af-897c-7b77b4aaf638.jpg)

**log file:**
![Screenshot 2022-04-07 133635](https://user-images.githubusercontent.com/49600677/162130165-7232b7ec-c712-44eb-9257-abe66ada278b.jpg)

#### Steps to Reproduce the Problem

  1. go to home
  2. click number of connected jason charge point button 
  3. error come at that page.

#### Additional context
no
...

**Comment by lategoodbye** [comment] 2022-04-09 11:44
@emry78 I'm using Version 3.4.9 and also to connected charge points, but i don't see the NullPointerException.
Do you see something special regarding to the charge points?
Can you provide the full stacktrace of the exception (especially the beginning is important)?

**Comment by goekay** [comment] 2022-04-10 12:11
yes. this screenshot is not helpful because the root cause of NPE is not there. it just depicts the lower layers of the exception.

**Comment by goekay** [comment] 2022-04-26 07:56
since there is no further activity/discussion, i am closing this issue.

**Closed by goekay** 2022-04-26 07:56 UTC
Labels: helpdesk
